name: null
favicon: null
layout_spectrum: 0.9723005117848516
typography_spectrum: 0.08362403488717973
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6681857826188207
  lightness: 0.5925074811093509
  saturation: 0.5103229016531259
  rhythmicContrast: 0.44100600969977677
purpose: []
