purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6702509
  brandStrength: 0.3125
  lightness: 0.7473118
  brandColors: []
  rhythmicContrast: 0.441006
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: click. edit. smile.
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.48763
layout_spectrum: 0.47693
